name = "XCBased"
uuid = "fac17066-6efe-4494-9398-e70f574ba8bc"
authors = ["MasFlam <masflam@masflam.com>"]
version = "0.1.4"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Xorg_libxcb_jll = "c7cfdc94-dc32-55de-ac96-5a1b8d977c5b"

[compat]
CEnum = "0.4"
Xorg_libxcb_jll = "1.13"
julia = "1.5"
