module Consts

import ..LibXCB

import ..LibXCB:
	X_PROTOCOL,
	X_PROTOCOL_REVISION,
	X_TCP_PORT,
	XCB_CONN_ERROR,
	XCB_CONN_CLOSED_EXT_NOTSUPPORTED,
	XCB_CONN_CLOSED_MEM_INSUFFICIENT,
	XCB_CONN_CLOSED_REQ_LEN_EXCEED,
	XCB_CONN_CLOSED_PARSE_ERR,
	XCB_CONN_CLOSED_INVALID_SCREEN,
	XCB_CONN_CLOSED_FDPASSING_FAILED

import ..LibXCB:
	XCB_NONE,
	XCB_COPY_FROM_PARENT,
	XCB_CURRENT_TIME,
	XCB_NO_SYMBOL

const XCB_VISUAL_CLASS_STATIC_GRAY = LibXCB.XCB_VISUAL_CLASS_STATIC_GRAY |> Integer
const XCB_VISUAL_CLASS_GRAY_SCALE = LibXCB.XCB_VISUAL_CLASS_GRAY_SCALE |> Integer
const XCB_VISUAL_CLASS_STATIC_COLOR = LibXCB.XCB_VISUAL_CLASS_STATIC_COLOR |> Integer
const XCB_VISUAL_CLASS_PSEUDO_COLOR = LibXCB.XCB_VISUAL_CLASS_PSEUDO_COLOR |> Integer
const XCB_VISUAL_CLASS_TRUE_COLOR = LibXCB.XCB_VISUAL_CLASS_TRUE_COLOR |> Integer
const XCB_VISUAL_CLASS_DIRECT_COLOR = LibXCB.XCB_VISUAL_CLASS_DIRECT_COLOR |> Integer

const XCB_EVENT_MASK_NO_EVENT = LibXCB.XCB_EVENT_MASK_NO_EVENT |> Integer
const XCB_EVENT_MASK_KEY_PRESS = LibXCB.XCB_EVENT_MASK_KEY_PRESS |> Integer
const XCB_EVENT_MASK_KEY_RELEASE = LibXCB.XCB_EVENT_MASK_KEY_RELEASE |> Integer
const XCB_EVENT_MASK_BUTTON_PRESS = LibXCB.XCB_EVENT_MASK_BUTTON_PRESS |> Integer
const XCB_EVENT_MASK_BUTTON_RELEASE = LibXCB.XCB_EVENT_MASK_BUTTON_RELEASE |> Integer
const XCB_EVENT_MASK_ENTER_WINDOW = LibXCB.XCB_EVENT_MASK_ENTER_WINDOW |> Integer
const XCB_EVENT_MASK_LEAVE_WINDOW = LibXCB.XCB_EVENT_MASK_LEAVE_WINDOW |> Integer
const XCB_EVENT_MASK_POINTER_MOTION = LibXCB.XCB_EVENT_MASK_POINTER_MOTION |> Integer
const XCB_EVENT_MASK_POINTER_MOTION_HINT = LibXCB.XCB_EVENT_MASK_POINTER_MOTION_HINT |> Integer
const XCB_EVENT_MASK_BUTTON_1_MOTION = LibXCB.XCB_EVENT_MASK_BUTTON_1_MOTION |> Integer
const XCB_EVENT_MASK_BUTTON_2_MOTION = LibXCB.XCB_EVENT_MASK_BUTTON_2_MOTION |> Integer
const XCB_EVENT_MASK_BUTTON_3_MOTION = LibXCB.XCB_EVENT_MASK_BUTTON_3_MOTION |> Integer
const XCB_EVENT_MASK_BUTTON_4_MOTION = LibXCB.XCB_EVENT_MASK_BUTTON_4_MOTION |> Integer
const XCB_EVENT_MASK_BUTTON_5_MOTION = LibXCB.XCB_EVENT_MASK_BUTTON_5_MOTION |> Integer
const XCB_EVENT_MASK_BUTTON_MOTION = LibXCB.XCB_EVENT_MASK_BUTTON_MOTION |> Integer
const XCB_EVENT_MASK_KEYMAP_STATE = LibXCB.XCB_EVENT_MASK_KEYMAP_STATE |> Integer
const XCB_EVENT_MASK_EXPOSURE = LibXCB.XCB_EVENT_MASK_EXPOSURE |> Integer
const XCB_EVENT_MASK_VISIBILITY_CHANGE = LibXCB.XCB_EVENT_MASK_VISIBILITY_CHANGE |> Integer
const XCB_EVENT_MASK_STRUCTURE_NOTIFY = LibXCB.XCB_EVENT_MASK_STRUCTURE_NOTIFY |> Integer
const XCB_EVENT_MASK_RESIZE_REDIRECT = LibXCB.XCB_EVENT_MASK_RESIZE_REDIRECT |> Integer
const XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY = LibXCB.XCB_EVENT_MASK_SUBSTRUCTURE_NOTIFY |> Integer
const XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT = LibXCB.XCB_EVENT_MASK_SUBSTRUCTURE_REDIRECT |> Integer
const XCB_EVENT_MASK_FOCUS_CHANGE = LibXCB.XCB_EVENT_MASK_FOCUS_CHANGE |> Integer
const XCB_EVENT_MASK_PROPERTY_CHANGE = LibXCB.XCB_EVENT_MASK_PROPERTY_CHANGE |> Integer
const XCB_EVENT_MASK_COLOR_MAP_CHANGE = LibXCB.XCB_EVENT_MASK_COLOR_MAP_CHANGE |> Integer
const XCB_EVENT_MASK_OWNER_GRAB_BUTTON = LibXCB.XCB_EVENT_MASK_OWNER_GRAB_BUTTON |> Integer

const XCB_BACKING_STORE_NOT_USEFUL = LibXCB.XCB_BACKING_STORE_NOT_USEFUL |> Integer
const XCB_BACKING_STORE_WHEN_MAPPED = LibXCB.XCB_BACKING_STORE_WHEN_MAPPED |> Integer
const XCB_BACKING_STORE_ALWAYS = LibXCB.XCB_BACKING_STORE_ALWAYS |> Integer

const XCB_IMAGE_ORDER_LSB_FIRST = LibXCB.XCB_IMAGE_ORDER_LSB_FIRST |> Integer
const XCB_IMAGE_ORDER_MSB_FIRST = LibXCB.XCB_IMAGE_ORDER_MSB_FIRST |> Integer

const XCB_MOD_MASK_SHIFT = LibXCB.XCB_MOD_MASK_SHIFT |> Integer
const XCB_MOD_MASK_LOCK = LibXCB.XCB_MOD_MASK_LOCK |> Integer
const XCB_MOD_MASK_CONTROL = LibXCB.XCB_MOD_MASK_CONTROL |> Integer
const XCB_MOD_MASK_1 = LibXCB.XCB_MOD_MASK_1 |> Integer
const XCB_MOD_MASK_2 = LibXCB.XCB_MOD_MASK_2 |> Integer
const XCB_MOD_MASK_3 = LibXCB.XCB_MOD_MASK_3 |> Integer
const XCB_MOD_MASK_4 = LibXCB.XCB_MOD_MASK_4 |> Integer
const XCB_MOD_MASK_5 = LibXCB.XCB_MOD_MASK_5 |> Integer
const XCB_MOD_MASK_ANY = LibXCB.XCB_MOD_MASK_ANY |> Integer

const XCB_KEY_BUT_MASK_SHIFT = LibXCB.XCB_KEY_BUT_MASK_SHIFT |> Integer
const XCB_KEY_BUT_MASK_LOCK = LibXCB.XCB_KEY_BUT_MASK_LOCK |> Integer
const XCB_KEY_BUT_MASK_CONTROL = LibXCB.XCB_KEY_BUT_MASK_CONTROL |> Integer
const XCB_KEY_BUT_MASK_MOD_1 = LibXCB.XCB_KEY_BUT_MASK_MOD_1 |> Integer
const XCB_KEY_BUT_MASK_MOD_2 = LibXCB.XCB_KEY_BUT_MASK_MOD_2 |> Integer
const XCB_KEY_BUT_MASK_MOD_3 = LibXCB.XCB_KEY_BUT_MASK_MOD_3 |> Integer
const XCB_KEY_BUT_MASK_MOD_4 = LibXCB.XCB_KEY_BUT_MASK_MOD_4 |> Integer
const XCB_KEY_BUT_MASK_MOD_5 = LibXCB.XCB_KEY_BUT_MASK_MOD_5 |> Integer
const XCB_KEY_BUT_MASK_BUTTON_1 = LibXCB.XCB_KEY_BUT_MASK_BUTTON_1 |> Integer
const XCB_KEY_BUT_MASK_BUTTON_2 = LibXCB.XCB_KEY_BUT_MASK_BUTTON_2 |> Integer
const XCB_KEY_BUT_MASK_BUTTON_3 = LibXCB.XCB_KEY_BUT_MASK_BUTTON_3 |> Integer
const XCB_KEY_BUT_MASK_BUTTON_4 = LibXCB.XCB_KEY_BUT_MASK_BUTTON_4 |> Integer
const XCB_KEY_BUT_MASK_BUTTON_5 = LibXCB.XCB_KEY_BUT_MASK_BUTTON_5 |> Integer

const XCB_WINDOW_NONE = LibXCB.XCB_WINDOW_NONE |> Integer

const XCB_BUTTON_MASK_1 = LibXCB.XCB_BUTTON_MASK_1 |> Integer
const XCB_BUTTON_MASK_2 = LibXCB.XCB_BUTTON_MASK_2 |> Integer
const XCB_BUTTON_MASK_3 = LibXCB.XCB_BUTTON_MASK_3 |> Integer
const XCB_BUTTON_MASK_4 = LibXCB.XCB_BUTTON_MASK_4 |> Integer
const XCB_BUTTON_MASK_5 = LibXCB.XCB_BUTTON_MASK_5 |> Integer
const XCB_BUTTON_MASK_ANY = LibXCB.XCB_BUTTON_MASK_ANY |> Integer

const XCB_MOTION_NORMAL = LibXCB.XCB_MOTION_NORMAL |> Integer
const XCB_MOTION_HINT = LibXCB.XCB_MOTION_HINT |> Integer

const XCB_NOTIFY_DETAIL_ANCESTOR = LibXCB.XCB_NOTIFY_DETAIL_ANCESTOR |> Integer
const XCB_NOTIFY_DETAIL_VIRTUAL = LibXCB.XCB_NOTIFY_DETAIL_VIRTUAL |> Integer
const XCB_NOTIFY_DETAIL_INFERIOR = LibXCB.XCB_NOTIFY_DETAIL_INFERIOR |> Integer
const XCB_NOTIFY_DETAIL_NONLINEAR = LibXCB.XCB_NOTIFY_DETAIL_NONLINEAR |> Integer
const XCB_NOTIFY_DETAIL_NONLINEAR_VIRTUAL = LibXCB.XCB_NOTIFY_DETAIL_NONLINEAR_VIRTUAL |> Integer
const XCB_NOTIFY_DETAIL_POINTER = LibXCB.XCB_NOTIFY_DETAIL_POINTER |> Integer
const XCB_NOTIFY_DETAIL_POINTER_ROOT = LibXCB.XCB_NOTIFY_DETAIL_POINTER_ROOT |> Integer
const XCB_NOTIFY_DETAIL_NONE = LibXCB.XCB_NOTIFY_DETAIL_NONE |> Integer

const XCB_NOTIFY_MODE_NORMAL = LibXCB.XCB_NOTIFY_MODE_NORMAL |> Integer
const XCB_NOTIFY_MODE_GRAB = LibXCB.XCB_NOTIFY_MODE_GRAB |> Integer
const XCB_NOTIFY_MODE_UNGRAB = LibXCB.XCB_NOTIFY_MODE_UNGRAB |> Integer
const XCB_NOTIFY_MODE_WHILE_GRABBED = LibXCB.XCB_NOTIFY_MODE_WHILE_GRABBED |> Integer

const XCB_VISIBILITY_UNOBSCURED = LibXCB.XCB_VISIBILITY_UNOBSCURED |> Integer
const XCB_VISIBILITY_PARTIALLY_OBSCURED = LibXCB.XCB_VISIBILITY_PARTIALLY_OBSCURED |> Integer
const XCB_VISIBILITY_FULLY_OBSCURED = LibXCB.XCB_VISIBILITY_FULLY_OBSCURED |> Integer

const XCB_PLACE_ON_TOP = LibXCB.XCB_PLACE_ON_TOP |> Integer
const XCB_PLACE_ON_BOTTOM = LibXCB.XCB_PLACE_ON_BOTTOM |> Integer

const XCB_PROPERTY_NEW_VALUE = LibXCB.XCB_PROPERTY_NEW_VALUE |> Integer
const XCB_PROPERTY_DELETE = LibXCB.XCB_PROPERTY_DELETE |> Integer

const XCB_TIME_CURRENT_TIME = LibXCB.XCB_TIME_CURRENT_TIME |> Integer

const XCB_ATOM_NONE = LibXCB.XCB_ATOM_NONE |> Integer
const XCB_ATOM_ANY = LibXCB.XCB_ATOM_ANY |> Integer
const XCB_ATOM_PRIMARY = LibXCB.XCB_ATOM_PRIMARY |> Integer
const XCB_ATOM_SECONDARY = LibXCB.XCB_ATOM_SECONDARY |> Integer
const XCB_ATOM_ARC = LibXCB.XCB_ATOM_ARC |> Integer
const XCB_ATOM_ATOM = LibXCB.XCB_ATOM_ATOM |> Integer
const XCB_ATOM_BITMAP = LibXCB.XCB_ATOM_BITMAP |> Integer
const XCB_ATOM_CARDINAL = LibXCB.XCB_ATOM_CARDINAL |> Integer
const XCB_ATOM_COLORMAP = LibXCB.XCB_ATOM_COLORMAP |> Integer
const XCB_ATOM_CURSOR = LibXCB.XCB_ATOM_CURSOR |> Integer
const XCB_ATOM_CUT_BUFFER0 = LibXCB.XCB_ATOM_CUT_BUFFER0 |> Integer
const XCB_ATOM_CUT_BUFFER1 = LibXCB.XCB_ATOM_CUT_BUFFER1 |> Integer
const XCB_ATOM_CUT_BUFFER2 = LibXCB.XCB_ATOM_CUT_BUFFER2 |> Integer
const XCB_ATOM_CUT_BUFFER3 = LibXCB.XCB_ATOM_CUT_BUFFER3 |> Integer
const XCB_ATOM_CUT_BUFFER4 = LibXCB.XCB_ATOM_CUT_BUFFER4 |> Integer
const XCB_ATOM_CUT_BUFFER5 = LibXCB.XCB_ATOM_CUT_BUFFER5 |> Integer
const XCB_ATOM_CUT_BUFFER6 = LibXCB.XCB_ATOM_CUT_BUFFER6 |> Integer
const XCB_ATOM_CUT_BUFFER7 = LibXCB.XCB_ATOM_CUT_BUFFER7 |> Integer
const XCB_ATOM_DRAWABLE = LibXCB.XCB_ATOM_DRAWABLE |> Integer
const XCB_ATOM_FONT = LibXCB.XCB_ATOM_FONT |> Integer
const XCB_ATOM_INTEGER = LibXCB.XCB_ATOM_INTEGER |> Integer
const XCB_ATOM_PIXMAP = LibXCB.XCB_ATOM_PIXMAP |> Integer
const XCB_ATOM_POINT = LibXCB.XCB_ATOM_POINT |> Integer
const XCB_ATOM_RECTANGLE = LibXCB.XCB_ATOM_RECTANGLE |> Integer
const XCB_ATOM_RESOURCE_MANAGER = LibXCB.XCB_ATOM_RESOURCE_MANAGER |> Integer
const XCB_ATOM_RGB_COLOR_MAP = LibXCB.XCB_ATOM_RGB_COLOR_MAP |> Integer
const XCB_ATOM_RGB_BEST_MAP = LibXCB.XCB_ATOM_RGB_BEST_MAP |> Integer
const XCB_ATOM_RGB_BLUE_MAP = LibXCB.XCB_ATOM_RGB_BLUE_MAP |> Integer
const XCB_ATOM_RGB_DEFAULT_MAP = LibXCB.XCB_ATOM_RGB_DEFAULT_MAP |> Integer
const XCB_ATOM_RGB_GRAY_MAP = LibXCB.XCB_ATOM_RGB_GRAY_MAP |> Integer
const XCB_ATOM_RGB_GREEN_MAP = LibXCB.XCB_ATOM_RGB_GREEN_MAP |> Integer
const XCB_ATOM_RGB_RED_MAP = LibXCB.XCB_ATOM_RGB_RED_MAP |> Integer
const XCB_ATOM_STRING = LibXCB.XCB_ATOM_STRING |> Integer
const XCB_ATOM_VISUALID = LibXCB.XCB_ATOM_VISUALID |> Integer
const XCB_ATOM_WINDOW = LibXCB.XCB_ATOM_WINDOW |> Integer
const XCB_ATOM_WM_COMMAND = LibXCB.XCB_ATOM_WM_COMMAND |> Integer
const XCB_ATOM_WM_HINTS = LibXCB.XCB_ATOM_WM_HINTS |> Integer
const XCB_ATOM_WM_CLIENT_MACHINE = LibXCB.XCB_ATOM_WM_CLIENT_MACHINE |> Integer
const XCB_ATOM_WM_ICON_NAME = LibXCB.XCB_ATOM_WM_ICON_NAME |> Integer
const XCB_ATOM_WM_ICON_SIZE = LibXCB.XCB_ATOM_WM_ICON_SIZE |> Integer
const XCB_ATOM_WM_NAME = LibXCB.XCB_ATOM_WM_NAME |> Integer
const XCB_ATOM_WM_NORMAL_HINTS = LibXCB.XCB_ATOM_WM_NORMAL_HINTS |> Integer
const XCB_ATOM_WM_SIZE_HINTS = LibXCB.XCB_ATOM_WM_SIZE_HINTS |> Integer
const XCB_ATOM_WM_ZOOM_HINTS = LibXCB.XCB_ATOM_WM_ZOOM_HINTS |> Integer
const XCB_ATOM_MIN_SPACE = LibXCB.XCB_ATOM_MIN_SPACE |> Integer
const XCB_ATOM_NORM_SPACE = LibXCB.XCB_ATOM_NORM_SPACE |> Integer
const XCB_ATOM_MAX_SPACE = LibXCB.XCB_ATOM_MAX_SPACE |> Integer
const XCB_ATOM_END_SPACE = LibXCB.XCB_ATOM_END_SPACE |> Integer
const XCB_ATOM_SUPERSCRIPT_X = LibXCB.XCB_ATOM_SUPERSCRIPT_X |> Integer
const XCB_ATOM_SUPERSCRIPT_Y = LibXCB.XCB_ATOM_SUPERSCRIPT_Y |> Integer
const XCB_ATOM_SUBSCRIPT_X = LibXCB.XCB_ATOM_SUBSCRIPT_X |> Integer
const XCB_ATOM_SUBSCRIPT_Y = LibXCB.XCB_ATOM_SUBSCRIPT_Y |> Integer
const XCB_ATOM_UNDERLINE_POSITION = LibXCB.XCB_ATOM_UNDERLINE_POSITION |> Integer
const XCB_ATOM_UNDERLINE_THICKNESS = LibXCB.XCB_ATOM_UNDERLINE_THICKNESS |> Integer
const XCB_ATOM_STRIKEOUT_ASCENT = LibXCB.XCB_ATOM_STRIKEOUT_ASCENT |> Integer
const XCB_ATOM_STRIKEOUT_DESCENT = LibXCB.XCB_ATOM_STRIKEOUT_DESCENT |> Integer
const XCB_ATOM_ITALIC_ANGLE = LibXCB.XCB_ATOM_ITALIC_ANGLE |> Integer
const XCB_ATOM_X_HEIGHT = LibXCB.XCB_ATOM_X_HEIGHT |> Integer
const XCB_ATOM_QUAD_WIDTH = LibXCB.XCB_ATOM_QUAD_WIDTH |> Integer
const XCB_ATOM_WEIGHT = LibXCB.XCB_ATOM_WEIGHT |> Integer
const XCB_ATOM_POINT_SIZE = LibXCB.XCB_ATOM_POINT_SIZE |> Integer
const XCB_ATOM_RESOLUTION = LibXCB.XCB_ATOM_RESOLUTION |> Integer
const XCB_ATOM_COPYRIGHT = LibXCB.XCB_ATOM_COPYRIGHT |> Integer
const XCB_ATOM_NOTICE = LibXCB.XCB_ATOM_NOTICE |> Integer
const XCB_ATOM_FONT_NAME = LibXCB.XCB_ATOM_FONT_NAME |> Integer
const XCB_ATOM_FAMILY_NAME = LibXCB.XCB_ATOM_FAMILY_NAME |> Integer
const XCB_ATOM_FULL_NAME = LibXCB.XCB_ATOM_FULL_NAME |> Integer
const XCB_ATOM_CAP_HEIGHT = LibXCB.XCB_ATOM_CAP_HEIGHT |> Integer
const XCB_ATOM_WM_CLASS = LibXCB.XCB_ATOM_WM_CLASS |> Integer
const XCB_ATOM_WM_TRANSIENT_FOR = LibXCB.XCB_ATOM_WM_TRANSIENT_FOR |> Integer

const XCB_COLORMAP_STATE_UNINSTALLED = LibXCB.XCB_COLORMAP_STATE_UNINSTALLED |> Integer
const XCB_COLORMAP_STATE_INSTALLED = LibXCB.XCB_COLORMAP_STATE_INSTALLED |> Integer

const XCB_COLORMAP_NONE = LibXCB.XCB_COLORMAP_NONE |> Integer

const XCB_MAPPING_MODIFIER = LibXCB.XCB_MAPPING_MODIFIER |> Integer
const XCB_MAPPING_KEYBOARD = LibXCB.XCB_MAPPING_KEYBOARD |> Integer
const XCB_MAPPING_POINTER = LibXCB.XCB_MAPPING_POINTER |> Integer

const XCB_WINDOW_CLASS_COPY_FROM_PARENT = LibXCB.XCB_WINDOW_CLASS_COPY_FROM_PARENT |> Integer
const XCB_WINDOW_CLASS_INPUT_OUTPUT = LibXCB.XCB_WINDOW_CLASS_INPUT_OUTPUT |> Integer
const XCB_WINDOW_CLASS_INPUT_ONLY = LibXCB.XCB_WINDOW_CLASS_INPUT_ONLY |> Integer

const XCB_CW_BACK_PIXMAP = LibXCB.XCB_CW_BACK_PIXMAP |> Integer
const XCB_CW_BACK_PIXEL = LibXCB.XCB_CW_BACK_PIXEL |> Integer
const XCB_CW_BORDER_PIXMAP = LibXCB.XCB_CW_BORDER_PIXMAP |> Integer
const XCB_CW_BORDER_PIXEL = LibXCB.XCB_CW_BORDER_PIXEL |> Integer
const XCB_CW_BIT_GRAVITY = LibXCB.XCB_CW_BIT_GRAVITY |> Integer
const XCB_CW_WIN_GRAVITY = LibXCB.XCB_CW_WIN_GRAVITY |> Integer
const XCB_CW_BACKING_STORE = LibXCB.XCB_CW_BACKING_STORE |> Integer
const XCB_CW_BACKING_PLANES = LibXCB.XCB_CW_BACKING_PLANES |> Integer
const XCB_CW_BACKING_PIXEL = LibXCB.XCB_CW_BACKING_PIXEL |> Integer
const XCB_CW_OVERRIDE_REDIRECT = LibXCB.XCB_CW_OVERRIDE_REDIRECT |> Integer
const XCB_CW_SAVE_UNDER = LibXCB.XCB_CW_SAVE_UNDER |> Integer
const XCB_CW_EVENT_MASK = LibXCB.XCB_CW_EVENT_MASK |> Integer
const XCB_CW_DONT_PROPAGATE = LibXCB.XCB_CW_DONT_PROPAGATE |> Integer
const XCB_CW_COLORMAP = LibXCB.XCB_CW_COLORMAP |> Integer
const XCB_CW_CURSOR = LibXCB.XCB_CW_CURSOR |> Integer

const XCB_BACK_PIXMAP_NONE = LibXCB.XCB_BACK_PIXMAP_NONE |> Integer
const XCB_BACK_PIXMAP_PARENT_RELATIVE = LibXCB.XCB_BACK_PIXMAP_PARENT_RELATIVE |> Integer

const XCB_GRAVITY_BIT_FORGET = LibXCB.XCB_GRAVITY_BIT_FORGET |> Integer
const XCB_GRAVITY_WIN_UNMAP = LibXCB.XCB_GRAVITY_WIN_UNMAP |> Integer
const XCB_GRAVITY_NORTH_WEST = LibXCB.XCB_GRAVITY_NORTH_WEST |> Integer
const XCB_GRAVITY_NORTH = LibXCB.XCB_GRAVITY_NORTH |> Integer
const XCB_GRAVITY_NORTH_EAST = LibXCB.XCB_GRAVITY_NORTH_EAST |> Integer
const XCB_GRAVITY_WEST = LibXCB.XCB_GRAVITY_WEST |> Integer
const XCB_GRAVITY_CENTER = LibXCB.XCB_GRAVITY_CENTER |> Integer
const XCB_GRAVITY_EAST = LibXCB.XCB_GRAVITY_EAST |> Integer
const XCB_GRAVITY_SOUTH_WEST = LibXCB.XCB_GRAVITY_SOUTH_WEST |> Integer
const XCB_GRAVITY_SOUTH = LibXCB.XCB_GRAVITY_SOUTH |> Integer
const XCB_GRAVITY_SOUTH_EAST = LibXCB.XCB_GRAVITY_SOUTH_EAST |> Integer
const XCB_GRAVITY_STATIC = LibXCB.XCB_GRAVITY_STATIC |> Integer

const XCB_MAP_STATE_UNMAPPED = LibXCB.XCB_MAP_STATE_UNMAPPED |> Integer
const XCB_MAP_STATE_UNVIEWABLE = LibXCB.XCB_MAP_STATE_UNVIEWABLE |> Integer
const XCB_MAP_STATE_VIEWABLE = LibXCB.XCB_MAP_STATE_VIEWABLE |> Integer

const XCB_SET_MODE_INSERT = LibXCB.XCB_SET_MODE_INSERT |> Integer
const XCB_SET_MODE_DELETE = LibXCB.XCB_SET_MODE_DELETE |> Integer

const XCB_CONFIG_WINDOW_X = LibXCB.XCB_CONFIG_WINDOW_X |> Integer
const XCB_CONFIG_WINDOW_Y = LibXCB.XCB_CONFIG_WINDOW_Y |> Integer
const XCB_CONFIG_WINDOW_WIDTH = LibXCB.XCB_CONFIG_WINDOW_WIDTH |> Integer
const XCB_CONFIG_WINDOW_HEIGHT = LibXCB.XCB_CONFIG_WINDOW_HEIGHT |> Integer
const XCB_CONFIG_WINDOW_BORDER_WIDTH = LibXCB.XCB_CONFIG_WINDOW_BORDER_WIDTH |> Integer
const XCB_CONFIG_WINDOW_SIBLING = LibXCB.XCB_CONFIG_WINDOW_SIBLING |> Integer
const XCB_CONFIG_WINDOW_STACK_MODE = LibXCB.XCB_CONFIG_WINDOW_STACK_MODE |> Integer

const XCB_STACK_MODE_ABOVE = LibXCB.XCB_STACK_MODE_ABOVE |> Integer
const XCB_STACK_MODE_BELOW = LibXCB.XCB_STACK_MODE_BELOW |> Integer
const XCB_STACK_MODE_TOP_IF = LibXCB.XCB_STACK_MODE_TOP_IF |> Integer
const XCB_STACK_MODE_BOTTOM_IF = LibXCB.XCB_STACK_MODE_BOTTOM_IF |> Integer
const XCB_STACK_MODE_OPPOSITE = LibXCB.XCB_STACK_MODE_OPPOSITE |> Integer

const XCB_CIRCULATE_RAISE_LOWEST = LibXCB.XCB_CIRCULATE_RAISE_LOWEST |> Integer
const XCB_CIRCULATE_LOWER_HIGHEST = LibXCB.XCB_CIRCULATE_LOWER_HIGHEST |> Integer

const XCB_PROP_MODE_REPLACE = LibXCB.XCB_PROP_MODE_REPLACE |> Integer
const XCB_PROP_MODE_PREPEND = LibXCB.XCB_PROP_MODE_PREPEND |> Integer
const XCB_PROP_MODE_APPEND = LibXCB.XCB_PROP_MODE_APPEND |> Integer

const XCB_GET_PROPERTY_TYPE_ANY = LibXCB.XCB_GET_PROPERTY_TYPE_ANY |> Integer

const XCB_SEND_EVENT_DEST_POINTER_WINDOW = LibXCB.XCB_SEND_EVENT_DEST_POINTER_WINDOW |> Integer
const XCB_SEND_EVENT_DEST_ITEM_FOCUS = LibXCB.XCB_SEND_EVENT_DEST_ITEM_FOCUS |> Integer

const XCB_GRAB_MODE_SYNC = LibXCB.XCB_GRAB_MODE_SYNC |> Integer
const XCB_GRAB_MODE_ASYNC = LibXCB.XCB_GRAB_MODE_ASYNC |> Integer

const XCB_GRAB_STATUS_SUCCESS = LibXCB.XCB_GRAB_STATUS_SUCCESS |> Integer
const XCB_GRAB_STATUS_ALREADY_GRABBED = LibXCB.XCB_GRAB_STATUS_ALREADY_GRABBED |> Integer
const XCB_GRAB_STATUS_INVALID_TIME = LibXCB.XCB_GRAB_STATUS_INVALID_TIME |> Integer
const XCB_GRAB_STATUS_NOT_VIEWABLE = LibXCB.XCB_GRAB_STATUS_NOT_VIEWABLE |> Integer
const XCB_GRAB_STATUS_FROZEN = LibXCB.XCB_GRAB_STATUS_FROZEN |> Integer

const XCB_CURSOR_NONE = LibXCB.XCB_CURSOR_NONE |> Integer

const XCB_BUTTON_INDEX_ANY = LibXCB.XCB_BUTTON_INDEX_ANY |> Integer
const XCB_BUTTON_INDEX_1 = LibXCB.XCB_BUTTON_INDEX_1 |> Integer
const XCB_BUTTON_INDEX_2 = LibXCB.XCB_BUTTON_INDEX_2 |> Integer
const XCB_BUTTON_INDEX_3 = LibXCB.XCB_BUTTON_INDEX_3 |> Integer
const XCB_BUTTON_INDEX_4 = LibXCB.XCB_BUTTON_INDEX_4 |> Integer
const XCB_BUTTON_INDEX_5 = LibXCB.XCB_BUTTON_INDEX_5 |> Integer

const XCB_GRAB_ANY = LibXCB.XCB_GRAB_ANY |> Integer

const XCB_ALLOW_ASYNC_POINTER = LibXCB.XCB_ALLOW_ASYNC_POINTER |> Integer
const XCB_ALLOW_SYNC_POINTER = LibXCB.XCB_ALLOW_SYNC_POINTER |> Integer
const XCB_ALLOW_REPLAY_POINTER = LibXCB.XCB_ALLOW_REPLAY_POINTER |> Integer
const XCB_ALLOW_ASYNC_KEYBOARD = LibXCB.XCB_ALLOW_ASYNC_KEYBOARD |> Integer
const XCB_ALLOW_SYNC_KEYBOARD = LibXCB.XCB_ALLOW_SYNC_KEYBOARD |> Integer
const XCB_ALLOW_REPLAY_KEYBOARD = LibXCB.XCB_ALLOW_REPLAY_KEYBOARD |> Integer
const XCB_ALLOW_ASYNC_BOTH = LibXCB.XCB_ALLOW_ASYNC_BOTH |> Integer
const XCB_ALLOW_SYNC_BOTH = LibXCB.XCB_ALLOW_SYNC_BOTH |> Integer

const XCB_INPUT_FOCUS_NONE = LibXCB.XCB_INPUT_FOCUS_NONE |> Integer
const XCB_INPUT_FOCUS_POINTER_ROOT = LibXCB.XCB_INPUT_FOCUS_POINTER_ROOT |> Integer
const XCB_INPUT_FOCUS_PARENT = LibXCB.XCB_INPUT_FOCUS_PARENT |> Integer
const XCB_INPUT_FOCUS_FOLLOW_KEYBOARD = LibXCB.XCB_INPUT_FOCUS_FOLLOW_KEYBOARD |> Integer

const XCB_FONT_DRAW_LEFT_TO_RIGHT = LibXCB.XCB_FONT_DRAW_LEFT_TO_RIGHT |> Integer
const XCB_FONT_DRAW_RIGHT_TO_LEFT = LibXCB.XCB_FONT_DRAW_RIGHT_TO_LEFT |> Integer

const XCB_GC_FUNCTION = LibXCB.XCB_GC_FUNCTION |> Integer
const XCB_GC_PLANE_MASK = LibXCB.XCB_GC_PLANE_MASK |> Integer
const XCB_GC_FOREGROUND = LibXCB.XCB_GC_FOREGROUND |> Integer
const XCB_GC_BACKGROUND = LibXCB.XCB_GC_BACKGROUND |> Integer
const XCB_GC_LINE_WIDTH = LibXCB.XCB_GC_LINE_WIDTH |> Integer
const XCB_GC_LINE_STYLE = LibXCB.XCB_GC_LINE_STYLE |> Integer
const XCB_GC_CAP_STYLE = LibXCB.XCB_GC_CAP_STYLE |> Integer
const XCB_GC_JOIN_STYLE = LibXCB.XCB_GC_JOIN_STYLE |> Integer
const XCB_GC_FILL_STYLE = LibXCB.XCB_GC_FILL_STYLE |> Integer
const XCB_GC_FILL_RULE = LibXCB.XCB_GC_FILL_RULE |> Integer
const XCB_GC_TILE = LibXCB.XCB_GC_TILE |> Integer
const XCB_GC_STIPPLE = LibXCB.XCB_GC_STIPPLE |> Integer
const XCB_GC_TILE_STIPPLE_ORIGIN_X = LibXCB.XCB_GC_TILE_STIPPLE_ORIGIN_X |> Integer
const XCB_GC_TILE_STIPPLE_ORIGIN_Y = LibXCB.XCB_GC_TILE_STIPPLE_ORIGIN_Y |> Integer
const XCB_GC_FONT = LibXCB.XCB_GC_FONT |> Integer
const XCB_GC_SUBWINDOW_MODE = LibXCB.XCB_GC_SUBWINDOW_MODE |> Integer
const XCB_GC_GRAPHICS_EXPOSURES = LibXCB.XCB_GC_GRAPHICS_EXPOSURES |> Integer
const XCB_GC_CLIP_ORIGIN_X = LibXCB.XCB_GC_CLIP_ORIGIN_X |> Integer
const XCB_GC_CLIP_ORIGIN_Y = LibXCB.XCB_GC_CLIP_ORIGIN_Y |> Integer
const XCB_GC_CLIP_MASK = LibXCB.XCB_GC_CLIP_MASK |> Integer
const XCB_GC_DASH_OFFSET = LibXCB.XCB_GC_DASH_OFFSET |> Integer
const XCB_GC_DASH_LIST = LibXCB.XCB_GC_DASH_LIST |> Integer
const XCB_GC_ARC_MODE = LibXCB.XCB_GC_ARC_MODE |> Integer

const XCB_GX_CLEAR = LibXCB.XCB_GX_CLEAR |> Integer
const XCB_GX_AND = LibXCB.XCB_GX_AND |> Integer
const XCB_GX_AND_REVERSE = LibXCB.XCB_GX_AND_REVERSE |> Integer
const XCB_GX_COPY = LibXCB.XCB_GX_COPY |> Integer
const XCB_GX_AND_INVERTED = LibXCB.XCB_GX_AND_INVERTED |> Integer
const XCB_GX_NOOP = LibXCB.XCB_GX_NOOP |> Integer
const XCB_GX_XOR = LibXCB.XCB_GX_XOR |> Integer
const XCB_GX_OR = LibXCB.XCB_GX_OR |> Integer
const XCB_GX_NOR = LibXCB.XCB_GX_NOR |> Integer
const XCB_GX_EQUIV = LibXCB.XCB_GX_EQUIV |> Integer
const XCB_GX_INVERT = LibXCB.XCB_GX_INVERT |> Integer
const XCB_GX_OR_REVERSE = LibXCB.XCB_GX_OR_REVERSE |> Integer
const XCB_GX_COPY_INVERTED = LibXCB.XCB_GX_COPY_INVERTED |> Integer
const XCB_GX_OR_INVERTED = LibXCB.XCB_GX_OR_INVERTED |> Integer
const XCB_GX_NAND = LibXCB.XCB_GX_NAND |> Integer
const XCB_GX_SET = LibXCB.XCB_GX_SET |> Integer

const XCB_LINE_STYLE_SOLID = LibXCB.XCB_LINE_STYLE_SOLID |> Integer
const XCB_LINE_STYLE_ON_OFF_DASH = LibXCB.XCB_LINE_STYLE_ON_OFF_DASH |> Integer
const XCB_LINE_STYLE_DOUBLE_DASH = LibXCB.XCB_LINE_STYLE_DOUBLE_DASH |> Integer

const XCB_CAP_STYLE_NOT_LAST = LibXCB.XCB_CAP_STYLE_NOT_LAST |> Integer
const XCB_CAP_STYLE_BUTT = LibXCB.XCB_CAP_STYLE_BUTT |> Integer
const XCB_CAP_STYLE_ROUND = LibXCB.XCB_CAP_STYLE_ROUND |> Integer
const XCB_CAP_STYLE_PROJECTING = LibXCB.XCB_CAP_STYLE_PROJECTING |> Integer

const XCB_JOIN_STYLE_MITER = LibXCB.XCB_JOIN_STYLE_MITER |> Integer
const XCB_JOIN_STYLE_ROUND = LibXCB.XCB_JOIN_STYLE_ROUND |> Integer
const XCB_JOIN_STYLE_BEVEL = LibXCB.XCB_JOIN_STYLE_BEVEL |> Integer

const XCB_FILL_STYLE_SOLID = LibXCB.XCB_FILL_STYLE_SOLID |> Integer
const XCB_FILL_STYLE_TILED = LibXCB.XCB_FILL_STYLE_TILED |> Integer
const XCB_FILL_STYLE_STIPPLED = LibXCB.XCB_FILL_STYLE_STIPPLED |> Integer
const XCB_FILL_STYLE_OPAQUE_STIPPLED = LibXCB.XCB_FILL_STYLE_OPAQUE_STIPPLED |> Integer

const XCB_FILL_RULE_EVEN_ODD = LibXCB.XCB_FILL_RULE_EVEN_ODD |> Integer
const XCB_FILL_RULE_WINDING = LibXCB.XCB_FILL_RULE_WINDING |> Integer

const XCB_SUBWINDOW_MODE_CLIP_BY_CHILDREN = LibXCB.XCB_SUBWINDOW_MODE_CLIP_BY_CHILDREN |> Integer
const XCB_SUBWINDOW_MODE_INCLUDE_INFERIORS = LibXCB.XCB_SUBWINDOW_MODE_INCLUDE_INFERIORS |> Integer

const XCB_ARC_MODE_CHORD = LibXCB.XCB_ARC_MODE_CHORD |> Integer
const XCB_ARC_MODE_PIE_SLICE = LibXCB.XCB_ARC_MODE_PIE_SLICE |> Integer

const XCB_CLIP_ORDERING_UNSORTED = LibXCB.XCB_CLIP_ORDERING_UNSORTED |> Integer
const XCB_CLIP_ORDERING_Y_SORTED = LibXCB.XCB_CLIP_ORDERING_Y_SORTED |> Integer
const XCB_CLIP_ORDERING_YX_SORTED = LibXCB.XCB_CLIP_ORDERING_YX_SORTED |> Integer
const XCB_CLIP_ORDERING_YX_BANDED = LibXCB.XCB_CLIP_ORDERING_YX_BANDED |> Integer

const XCB_COORD_MODE_ORIGIN = LibXCB.XCB_COORD_MODE_ORIGIN |> Integer
const XCB_COORD_MODE_PREVIOUS = LibXCB.XCB_COORD_MODE_PREVIOUS |> Integer

const XCB_POLY_SHAPE_COMPLEX = LibXCB.XCB_POLY_SHAPE_COMPLEX |> Integer
const XCB_POLY_SHAPE_NONCONVEX = LibXCB.XCB_POLY_SHAPE_NONCONVEX |> Integer
const XCB_POLY_SHAPE_CONVEX = LibXCB.XCB_POLY_SHAPE_CONVEX |> Integer

const XCB_IMAGE_FORMAT_XY_BITMAP = LibXCB.XCB_IMAGE_FORMAT_XY_BITMAP |> Integer
const XCB_IMAGE_FORMAT_XY_PIXMAP = LibXCB.XCB_IMAGE_FORMAT_XY_PIXMAP |> Integer
const XCB_IMAGE_FORMAT_Z_PIXMAP = LibXCB.XCB_IMAGE_FORMAT_Z_PIXMAP |> Integer

const XCB_COLORMAP_ALLOC_NONE = LibXCB.XCB_COLORMAP_ALLOC_NONE |> Integer
const XCB_COLORMAP_ALLOC_ALL = LibXCB.XCB_COLORMAP_ALLOC_ALL |> Integer

const XCB_COLOR_FLAG_RED = LibXCB.XCB_COLOR_FLAG_RED |> Integer
const XCB_COLOR_FLAG_GREEN = LibXCB.XCB_COLOR_FLAG_GREEN |> Integer
const XCB_COLOR_FLAG_BLUE = LibXCB.XCB_COLOR_FLAG_BLUE |> Integer

const XCB_PIXMAP_NONE = LibXCB.XCB_PIXMAP_NONE |> Integer

const XCB_FONT_NONE = LibXCB.XCB_FONT_NONE |> Integer

const XCB_QUERY_SHAPE_OF_LARGEST_CURSOR = LibXCB.XCB_QUERY_SHAPE_OF_LARGEST_CURSOR |> Integer
const XCB_QUERY_SHAPE_OF_FASTEST_TILE = LibXCB.XCB_QUERY_SHAPE_OF_FASTEST_TILE |> Integer
const XCB_QUERY_SHAPE_OF_FASTEST_STIPPLE = LibXCB.XCB_QUERY_SHAPE_OF_FASTEST_STIPPLE |> Integer

const XCB_KB_KEY_CLICK_PERCENT = LibXCB.XCB_KB_KEY_CLICK_PERCENT |> Integer
const XCB_KB_BELL_PERCENT = LibXCB.XCB_KB_BELL_PERCENT |> Integer
const XCB_KB_BELL_PITCH = LibXCB.XCB_KB_BELL_PITCH |> Integer
const XCB_KB_BELL_DURATION = LibXCB.XCB_KB_BELL_DURATION |> Integer
const XCB_KB_LED = LibXCB.XCB_KB_LED |> Integer
const XCB_KB_LED_MODE = LibXCB.XCB_KB_LED_MODE |> Integer
const XCB_KB_KEY = LibXCB.XCB_KB_KEY |> Integer
const XCB_KB_AUTO_REPEAT_MODE = LibXCB.XCB_KB_AUTO_REPEAT_MODE |> Integer

const XCB_LED_MODE_OFF = LibXCB.XCB_LED_MODE_OFF |> Integer
const XCB_LED_MODE_ON = LibXCB.XCB_LED_MODE_ON |> Integer

const XCB_AUTO_REPEAT_MODE_OFF = LibXCB.XCB_AUTO_REPEAT_MODE_OFF |> Integer
const XCB_AUTO_REPEAT_MODE_ON = LibXCB.XCB_AUTO_REPEAT_MODE_ON |> Integer
const XCB_AUTO_REPEAT_MODE_DEFAULT = LibXCB.XCB_AUTO_REPEAT_MODE_DEFAULT |> Integer

const XCB_BLANKING_NOT_PREFERRED = LibXCB.XCB_BLANKING_NOT_PREFERRED |> Integer
const XCB_BLANKING_PREFERRED = LibXCB.XCB_BLANKING_PREFERRED |> Integer
const XCB_BLANKING_DEFAULT = LibXCB.XCB_BLANKING_DEFAULT |> Integer

const XCB_EXPOSURES_NOT_ALLOWED = LibXCB.XCB_EXPOSURES_NOT_ALLOWED |> Integer
const XCB_EXPOSURES_ALLOWED = LibXCB.XCB_EXPOSURES_ALLOWED |> Integer
const XCB_EXPOSURES_DEFAULT = LibXCB.XCB_EXPOSURES_DEFAULT |> Integer

const XCB_HOST_MODE_INSERT = LibXCB.XCB_HOST_MODE_INSERT |> Integer
const XCB_HOST_MODE_DELETE = LibXCB.XCB_HOST_MODE_DELETE |> Integer

const XCB_FAMILY_INTERNET = LibXCB.XCB_FAMILY_INTERNET |> Integer
const XCB_FAMILY_DECNET = LibXCB.XCB_FAMILY_DECNET |> Integer
const XCB_FAMILY_CHAOS = LibXCB.XCB_FAMILY_CHAOS |> Integer
const XCB_FAMILY_SERVER_INTERPRETED = LibXCB.XCB_FAMILY_SERVER_INTERPRETED |> Integer
const XCB_FAMILY_INTERNET_6 = LibXCB.XCB_FAMILY_INTERNET_6 |> Integer

const XCB_ACCESS_CONTROL_DISABLE = LibXCB.XCB_ACCESS_CONTROL_DISABLE |> Integer
const XCB_ACCESS_CONTROL_ENABLE = LibXCB.XCB_ACCESS_CONTROL_ENABLE |> Integer

const XCB_CLOSE_DOWN_DESTROY_ALL = LibXCB.XCB_CLOSE_DOWN_DESTROY_ALL |> Integer
const XCB_CLOSE_DOWN_RETAIN_PERMANENT = LibXCB.XCB_CLOSE_DOWN_RETAIN_PERMANENT |> Integer
const XCB_CLOSE_DOWN_RETAIN_TEMPORARY = LibXCB.XCB_CLOSE_DOWN_RETAIN_TEMPORARY |> Integer

const XCB_KILL_ALL_TEMPORARY = LibXCB.XCB_KILL_ALL_TEMPORARY |> Integer

const XCB_SCREEN_SAVER_RESET = LibXCB.XCB_SCREEN_SAVER_RESET |> Integer
const XCB_SCREEN_SAVER_ACTIVE = LibXCB.XCB_SCREEN_SAVER_ACTIVE |> Integer

const XCB_MAPPING_STATUS_SUCCESS = LibXCB.XCB_MAPPING_STATUS_SUCCESS |> Integer
const XCB_MAPPING_STATUS_BUSY = LibXCB.XCB_MAPPING_STATUS_BUSY |> Integer
const XCB_MAPPING_STATUS_FAILURE = LibXCB.XCB_MAPPING_STATUS_FAILURE |> Integer

const XCB_MAP_INDEX_SHIFT = LibXCB.XCB_MAP_INDEX_SHIFT |> Integer
const XCB_MAP_INDEX_LOCK = LibXCB.XCB_MAP_INDEX_LOCK |> Integer
const XCB_MAP_INDEX_CONTROL = LibXCB.XCB_MAP_INDEX_CONTROL |> Integer
const XCB_MAP_INDEX_1 = LibXCB.XCB_MAP_INDEX_1 |> Integer
const XCB_MAP_INDEX_2 = LibXCB.XCB_MAP_INDEX_2 |> Integer
const XCB_MAP_INDEX_3 = LibXCB.XCB_MAP_INDEX_3 |> Integer
const XCB_MAP_INDEX_4 = LibXCB.XCB_MAP_INDEX_4 |> Integer
const XCB_MAP_INDEX_5 = LibXCB.XCB_MAP_INDEX_5 |> Integer

end # module
